name: Flask Jira Integration Workflow

# Trigger the workflow on push to the main branch

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests flask

      - name: Run Flask App
        env: 
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          python create_jira_ticket_app.py
        
