name: Flask Jira Integration Workflow

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'

      - name: Install dependencies and set up virtual environment
        run: |
          # Go into the correct folder
          cd Create_virtual_env_install_python_and_flask
          
          # Run the shell script to install Python, virtualenv, and Flask
          chmod +x install_python_virtual_env_and_flask.sh
          ./install_python_virtual_env_and_flask.sh
          
          # Go into the Flask app directory
          cd my_flask_app
          
          # Ensure the virtual environment is created
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          
          # Activate the virtual environment
          source venv/bin/activate

      - name: Run Flask App
        env: 
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          # Navigate to the Flask app directory
          cd Create_virtual_env_install_python_and_flask/my_flask_app

          # Run the Flask application
          python create_jira_ticket_app.py
